# Generated by Django 5.0.4 on 2024-05-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_app', '0003_remove_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='category',
            field=models.ManyToManyField(related_name='Books', to='bookstore_app.category'),
        ),
    ]
